steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
      - .
      - '-f'
      - Dockerfile
    id: Build
images:
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LOCATION: us-west2
  _PROJECT_ID: ita-datalakepoc
  _REPOSITORY: covid19-indicators
  _IMAGE: TestImg


