steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: '.'
    args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}']
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run',
  #           'deploy',
  #           '${_SERVICE1}',
  #           '--region=${_LOCATION}',
  #           '--platform=managed',
  #           '--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}']
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run',
  #           'deploy',
  #           '${_SERVICE2}',
  #           '--region=${_LOCATION}',
  #           '--platform=managed',
  #           '--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}']
timeout: 6000s

# Substitution variables in Cloud Build Trigger
# _LOCATION=us-west2
# _REPOSITORY=covid19-indicators
# _IMAGE=artifact-registry-cloud-build
# _SERVICE1=tf-covid19-indicators-stage-1
# _SERVICE2=tf-covid19-indicators-stage-2
